# Site Variables
title: Theisen
url: http://theisensanders.com
thumbnail: /assets/img/theisen.png
description: >
    Ideas and thoughts of software developer Theisen Sanders

# Build Variables
permalink: /blog/:title
markdown: redcarpet