markdown:      maruku
markdown_ext:  md

permalink: /blog/posts/:title

url: http://theisensanders.com
title: Theisen Sanders
subtitle: idk
author: Theisen Sanders
simple_search: google
description: The personal website of Theisen Sanders
google_analytics: UA-33670860-3