title: Theisen Sanders
short_title: Theisen
url: http://theisensanders.com
thumbnail: /assets/img/portrait.png
description: >
    A web development and design playground for software developer Theisen Sanders


permalink: /playground/:title
markdown: redcarpet
redcarpet:
  extensions: [tables, strikethrough]

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
    - package.json
    - gulpfile.js
    - CNAME
    - node_modules